language: go
go:
  - 1.2
  - tip
script:
  - go test ./...
  - ./gofmt_check.sh
  - ./cli_test.sh
install:
  go get -v ./...
KEY_PASSWORD:
  secure: Np0pRS9Xp0ojSaNU4Cu/aic3i3oKooicUYjGTyb0z9OQ4jwmdKvo9cWlKoKXcPzqd/QgblvxCs5+fE/OX25brApGFQh8NjmlGbDBQ0V1ndzuJ9vHHAGVOsoemhoYlUWU9Dabw0mn3+dOo7HrqlUACIGlkgVp5KjxCPmsK1rIN6k=
