language: go
go:
  - 1.2
  - tip
script:
  - go test ./...
  - ./gofmt_check.sh
  - ./cli_test.sh
install:
  go get -v ./...
env:
  global:
    - secure: "Tnbpk989dMErUAyJHJJwTuLQ0Z145Py9/fr2mN2wfcKussI7RYkT9kh9104YO4sox+lfFLHyefdWrgLZOXlq/2q1OwG2UqJaHmpRNj29JCF1siy3PbmruIbSAedAhu/waIhteoqDn2iLEv7m5BmkemDif4aAMNdz4EcIL+y0dog="
